spring:
  application:
    name: lectureq
  profiles:
    active: local

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 1800000
  refresh-expiration: 1209600000

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
